/*
 * Copyright (c) 2021, ARM Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef MTK_PLL_REG_H
#define MTK_PLL_REG_H

#include <mt6750_def.h>

#define APMIXED_BASE		(IO_BASE + 0xC000)
#define CKSYS_BASE		IO_BASE
#define INFRACFG_AO_BASE	(IO_BASE + 0x1000)

#define PLL_PWR			BIT(0)
#define PLL_EN			BIT(0)
#define PLL_ISO_MASK		BIT(1)
#define PLL_FDBK_DIV_UP		BIT(31)
#define PLL_DIV_RST_BAR		BIT(24)

#define CLKSQ_STB_CON0		(APMIXED_BASE + 0x20)
#define PLL_ISO_CON0 		(APMIXED_BASE + 0x2C)
#define AP_PLL_CON3		(APMIXED_BASE + 0x0C)
#define AP_PLL_CON4		(APMIXED_BASE + 0x10)
#define AP_PLL_CON6		(APMIXED_BASE + 0x18)

#define ARMCA15PLL_CON0		(APMIXED_BASE + 0x200)
#define ARMCA15PLL_CON1		(APMIXED_BASE + 0x204)
#define ARMCA15PLL_PWR_CON0	(APMIXED_BASE + 0x20C)
#define ARMCA15PLL_POSTDIV2	BIT(24)
#define ARMCA15PLL_FDBK_DIV	0x10C000

#define ARMCA7PLL_CON0		(APMIXED_BASE + 0x210)
#define ARMCA7PLL_CON1		(APMIXED_BASE + 0x214)
#define ARMCA7PLL_PWR_CON0	(APMIXED_BASE + 0x21C)
#define ARMCA7PLL_POSTDIV2	BIT(24)
#define ARMCA7PLL_FDBK_DIV	0xD4000

#define MAINPLL_CON0		(APMIXED_BASE + 0x220)
#define MAINPLL_CON1		(APMIXED_BASE + 0x224)
#define MAINPLL_PWR_CON0	(APMIXED_BASE + 0x22C)
#define MAINPLL_FDBK_DIV	0xA8000

#define UNIVPLL_CON0		(APMIXED_BASE + 0x230)
#define UNIVPLL_CON1		(APMIXED_BASE + 0x234)
#define UNIVPLL_PWR_CON0	(APMIXED_BASE + 0x23C)

#define MMPLL_CON0		(APMIXED_BASE + 0x240)
#define MMPLL_CON1		(APMIXED_BASE + 0x244)
#define MMPLL_PWR_CON0		(APMIXED_BASE + 0x24C)
#define MMPLL_POSTDIV4		BIT(25)
#define MMPLL_FDBK_DIV		0x140000

#define MSDCPLL_CON0		(APMIXED_BASE + 0x250)
#define MSDCPLL_CON1		(APMIXED_BASE + 0x254)
#define MSDCPLL_PWR_CON0	(APMIXED_BASE + 0x25C)
#define MSDCPLL_FDBK_DIV	0xEC000

#define VENCPLL_CON0		(APMIXED_BASE + 0x260)
#define VENCPLL_CON1		(APMIXED_BASE + 0x264)
#define VENCPLL_PWR_CON0	(APMIXED_BASE + 0x26C)
#define VENCPLL_POSTDIV4	0x120
#define VENCPLL_FDBK_DIV	0xB0000

#define TVDPLL_CON0		(APMIXED_BASE + 0x270)
#define TVDPLL_CON1		(APMIXED_BASE + 0x274)
#define TVDPLL_PWR_CON0		(APMIXED_BASE + 0x27C)
#define TVDPLL_FDBK_DIV		0x16D89E

#define MPLL_CON1		(APMIXED_BASE + 0x284)
#define MPLL_PWR_CON0		(APMIXED_BASE + 0x28C)

#define VCODECPLL_CON1		(APMIXED_BASE + 0x294)
#define VCODECPLL_PWR_CON0		(APMIXED_BASE + 0x29C)

#define APLL1_CON0		(APMIXED_BASE + 0x2A0)
#define APLL1_CON1		(APMIXED_BASE + 0x2A4)
#define APLL1_PWR_CON0		(APMIXED_BASE + 0x2B0)

#define APLL2_CON0		(APMIXED_BASE + 0x2B4)
#define APLL2_CON1		(APMIXED_BASE + 0x2B8)
#define APLL2_PWR_CON0		(APMIXED_BASE + 0x2C4)

#define CLK_CFG_UPDATE		(CKSYS_BASE + 0x004)
#define CLK_CFG_UPDATE1		(CKSYS_BASE + 0x008)
#define CLK_CFG_0		(CKSYS_BASE + 0x040)
#define CLK_CFG_1		(CKSYS_BASE + 0x050)
#define CLK_CFG_2		(CKSYS_BASE + 0x060)
#define CLK_CFG_3		(CKSYS_BASE + 0x070)
#define CLK_CFG_4		(CKSYS_BASE + 0x080)
#define CLK_CFG_5		(CKSYS_BASE + 0x090)
#define CLK_CFG_6		(CKSYS_BASE + 0x0A0)
#define CLK_CFG_7		(CKSYS_BASE + 0x0B0)
#define CLK_CFG_8		(CKSYS_BASE + 0x0C0)
#define CLK_SCP_CFG_0		(CKSYS_BASE + 0x200)
#define CLK_SCP_CFG_1		(CKSYS_BASE + 0x204)

#define TOP_CKMUXSEL		(INFRACFG_AO_BASE + 0x00)
#define ARMCA7PLL_MUX_ARMPLL	BIT(0)
#define ARMCA15PLL_MUX_ARMPLL	BIT(2)
#define BIG_ARMPLL_MUX_ARMBPLL	BIT(4)
#define SML_ARMPLL_MUX_ARMSPLL	BIT(8)
#define CCI_MUX_ARMBPLL		BIT(13)

#define TOP_CKDIV1_BIG		(INFRACFG_AO_BASE + 0x24)
#define ARMBPLL_CLK_DIV_MASK	GENMASK(4, 0)

#define TOP_CKDIV1_SML		(INFRACFG_AO_BASE + 0x28)
#define ARMSPLL_CLK_DIV_MASK	GENMASK(4, 0)

#define TOP_CKDIV1_BUS		(INFRACFG_AO_BASE + 0x2C)
#define CCI_CLK_DIV_MASK	GENMASK(4, 0)
#define CCI_CLK_DIV2		0xA

#define TOP_DCMCTL		(INFRACFG_AO_BASE + 0x10)
#define INFRA_BUS_DCM_EN	BIT(0)

#define INFRA_BUS_DCM_CTRL	(INFRACFG_AO_BASE + 0x70)
#define SPM_DCM_EN		BIT(21)

#define ACLKEN_DIV		(IO_BASE + 0x200640)
#define AXI_DIV2		0x12

#define INFRA_PDN_CLR0		(INFRACFG_AO_BASE + 0x0084)
#define INFRA_PDN_CLR1		(INFRACFG_AO_BASE + 0x008C)
#define INFRA_PDN_CLR2		(INFRACFG_AO_BASE + 0x00A8)

#endif //MTK_PLL_REG_H

